config/routes.rb
Rails.application.routes.draw do
  get 'gossip/new', to: 'gossip#new', as: 'gossip_new'
  get 'gossip/:id', to: 'gossip#show', as: 'gossip'

  post 'gossip/new', to: 'gossip#create', as: 'gossip_create'

  get 'gossip/edit/:id', to: 'gossip#edit', as: 'gossip_edit'
  post 'gossip/edit/:id', to: 'gossip#modify', as: 'modify'

  get '/all', to: 'gossip#all', as: 'all'

  get '/delete', to: 'gossip#delete', as: 'delete'
  delete '/destroy', to: 'gossip#destroy', as: 'destroy'
  
  root 'static_pages#home'
  resources :static_pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def new
  end
  def create
    @gossip = Gossip.new
    @gossip.anonymous_author = params[:username]
    @gossip.content = params[:content]
    @gossip.save
    puts params
    redirect_to @gossip
  end

  def show
    @gossip = Gossip.find_by(id: params[:id])
  end

  def edit
  end

  def modify
    @gossip = Gossip.find_by(id: params[:id])
    @gossip.anonymous_author = params[:username]
    @gossip.content = params[:content]
    @gossip.save
    redirect_to @gossip
  end

  def all
    @gossip = Gossip.all
  end

  def destroy
    @gossip = Gossip.find_by(params[:id])
    @gossip.destroy
    redirect_to all_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gossip/all.html.erb
<%= render 'layouts/navbar'%>
<div class="conteneur">
  <h1>Index des Gossips, oh yeah</h1>
  <p></p>
  <table class="conteneur">
    <thead> <tr>
             <th></th>
         </tr></thead>
    <tbody>
  <% @gossip.each do |gossip| %>


        <tr>
          <td>
          <h5><a href="gossip/<%= gossip.id %>" > <%= gossip.content %> </a><a href="<%= destroy_path %>" class="btn btn-danger btn-sm" data-method="DELETE">X</a>
</h5>
          <br>
          

        </td>
        </tr>
  <% end %>
  </tbody>
  </table>
</div>

app/views/gossip/edit.html.erb
<%= render 'layouts/navbar'%>
<div class="conteneur">
  <h2> Edition de votre gossip : </h2>
<form action="<%=modify_path%>" method= "POST" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="form-group">
    <label for="name">Pseudo:</label>
    <input name="username" style="width:200px; margin: 0 auto;">
  </div>
  <label for="content">Gossip ?</label>
  <div class="form-group">

    <textarea name="content" style="width:200px; height: 200px;"></textarea>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

app/views/gossip/new.html.erb
<%= render 'layouts/navbar'%>
<div class="conteneur">
<form action="<%=gossip_create_path%>" method= "POST" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="form-group">
    <label for="name">Pseudo:</label>
    <input type="name" class="form-control" id="name" style="width:200px; margin: 0 auto;">
  </div>
  <label for="content">Gossip ?</label>
  <div class="form-group">

    <textarea name="content" style="width:200px; height: 200px;"></textarea>
  </div>
  <div class="form-group form-check">
    <label class="form-check-label">
      <input class="form-check-input" type="checkbox"> Remember me
    </label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

app/views/gossip/show.html.erb
<%= render 'layouts/navbar'%>
<div class="conteneur">
<h1>Votre gossip :</h1>
<p>  <%= @gossip.content %> </p></br>

<a href="<%= gossip_edit_path%>"><button type="button" class="btn btn-info" >Edit </button></a> &nbsp
<a href="<%= gossip_new_path%>"><button type="button" class="btn btn-primary">Create </button></a>
<a href="<%= all_path%>"><button type="button" class="btn btn-warning">All the gossips</button></a> &nbsp
<a href="<%= destroy_path %>" class="btn btn-danger" data-method="DELETE">Delete </a>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Gossip, Bitch</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <!-- <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li> -->
        <li><a href="<%= gossip_new_path%>">Création d'un gossip</a></li>
        <li><a href="<%= all_path%>">Tous les gossips</a></li>
        <li><a href="#">Lien vide</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<%= render 'layouts/navbar'%>
<div class="conteneur">
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Regarde la nav bar pour essayer les différentes fonctions du site !
  </h3>

</div>
</div>